Nezih
SkanderLassoued09/fix-back pull request #1
Opened 2024-02-26 20:00 UTC by MrNezihBJ

All entities except Demande d'intervention

2024-02-26 20:20 UTC, SkanderLassoued09 requested changes
You should follow one approach in writing variables and classes 
You should you comments to define every field and function

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/clients/dto/update-client.input.ts
> +
Please remove unused files

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/clients/entities/client.entity.ts
> +import { ObjectType, Field, Int } from '@nestjs/graphql';
Please change code : 
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';

export type CatDocument = HydratedDocument<Cat>; // you can remove this line

@Schema()
export class Cat { // CatDocument
  @Prop()
  name: string;

  @Prop()
  age: number;

  @Prop()
  breed: string;
}

export const CatSchema = SchemaFactory.createForClass(Cat); // CatDocument

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/clients/entities/client.entity.ts
> +  {
Please change code : 
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';

export type CatDocument = HydratedDocument<Cat>; // you can remove this line

@Schema()
export class Cat { // CatDocument
  @Prop()
  name: string;

  @Prop()
  age: number;

  @Prop()
  breed: string;
}

export const CatSchema = SchemaFactory.createForClass(Cat); // CatDocument

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/companies/companies.resolver.ts
> +@Resolver(() => Companie)
Please change companie with company

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/companies/companies.resolver.ts
> +  async createCompanie(
Please change companie with company

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/companies/companies.service.ts
> +export class CompaniesService {
Please change companie with company

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/companies/dto/create-company.input.ts
> +export class CreateCompanieInput {
Please change companie with company

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/companies/dto/create-company.input.ts
> +  webSiteLink: string;
Please remove unused comments

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/companies/entities/company.entity.ts
> +  {
Same new declaration as mentioned before

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/companies/entities/company.entity.ts
> +export class service_Achat_Tech_Financier {
Class name should be in Majuscule

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/companies/entities/company.entity.ts
> +export class Companie extends Document {
Please change companie with company

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/composant/dto/create-composant.input.ts
> +  @Field()
All fields should be in english or in frensh please

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/composant/dto/update-composant.input.ts
> +import { InputType, Field, Int, PartialType } from '@nestjs/graphql';
Remove unused comments

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/composant/entities/composant.entity.ts
> +export type ComposantDocument = Composant & Document;
Same declaration as mention before

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/composant/entities/composant.entity.ts
> +  pdf: string;
Specify which PDF you talk about

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/composant/entities/composant.entity.ts
> +  status: string;
Specify which status you talk about

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/composant_categorie/composant_categorie.module.ts
> +        name: 'Composant_Categorie',
Please change categorie by category

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/composant_categorie/composant_categorie.resolver.ts
> +  @Mutation(() => Composant_Categorie)
please choose one approach ComposantCategory or composant_category

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/composant_categorie/composant_categorie.resolver.ts
> +    } catch (error) {
Remove try and catch

2024-02-26 20:20 UTC, SkanderLassoued09 commented on src/composant_categorie/entities/composant_categorie.entity.ts
> +export const Composant_CategorieSchema = new mongoose.Schema(
Same declaration as mentioned before

2024-02-29 11:57 UTC, MrNezihBJ commented on src/companies/companies.resolver.ts
> +  async createCompanie(
Done

2024-02-29 11:57 UTC, MrNezihBJ commented on src/companies/companies.resolver.ts
> +@Resolver(() => Companie)
Done

2024-02-29 20:48 UTC, SkanderLassoued09 approved these changes

2024-02-29 20:49 UTC, merged